# Generated by Django 3.0.dev20190125164321 on 2019-01-29 00:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_shareable',
            field=models.BooleanField(default=False, verbose_name='is_shareable'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 1, 29, 0, 2, 59, 188166, tzinfo=utc), verbose_name='time'),
        ),
    ]
