# Generated by Django 3.0.dev20190125164321 on 2019-01-29 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0003_auto_20190129_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 29, 21, 32, 22, 811940), verbose_name='time'),
        ),
    ]
